### ISSUE TITLE
about pre-trained models

### ISSUE THREAD

**Issue by meng-zm** [JiabenChen/iQuery#2]

**Comment by meng-zm** [comment]
Hi, thanks for the interesting work!

Could you provide the ckpt files of pre-trained models? I mean R(2+1)D on Kinetics-400, UCF-101 and HMD51, I3D on HMD51.

Thanks!

**Comment by JiabenChen** [comment]
Are you referring to the pre-trained model of the motion video encoder? You can find the pre-trained I3D models at the repo of FAME: https://github.com/Mark12Ding/FAME
